"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { api } from "@/lib/api";
import { Card, EmptyState } from "@/components/ui/Card";

export default function ReelStoryboardPage() {
  const { jobId } = useParams<{ jobId: string }>();
  const [board, setBoard] = useState<any>(null);
  const [direction, setDirection] = useState<any>(null);
  const [arts, setArts] = useState<string[]>([]);
  const [loaded, setLoaded] = useState(false);
  useEffect(() => {
    fetch(api.artifactUrl(jobId, "07_storyboard.json")).then((x) => x.ok ? x.json() : null).then(setBoard).catch(() => {}).finally(() => setLoaded(true));
    fetch(api.artifactUrl(jobId, "08_visual_direction.json")).then((x) => x.ok ? x.json() : null).then(setDirection).catch(() => {});
    api.artifacts(jobId).then((a) => setArts(a.artifacts.map((x) => x.name))).catch(() => {});
  }, [jobId]);

  if (loaded && !board) return <div className="px-6 py-8 max-w-5xl mx-auto"><EmptyState title="No storyboard artifact" /></div>;
  const scenes = board?.scenes ?? [];
  const hasCover = arts.includes("cover.jpg");

  return (
    <div className="px-6 py-6 max-w-5xl mx-auto space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <div className="eyebrow">Storyboard + Visual Director + Cover Frame</div>
          <h2 className="text-xl font-semibold tracking-tight mt-1">{scenes.length} scenes · {board?.total_seconds}s</h2>
        </div>
        {direction?.selected && <span className="chip border-line text-ink-muted">{direction.selected}</span>}
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
        {hasCover && (
          <div className="glass overflow-hidden">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={api.artifactUrl(jobId, "cover.jpg")} alt="cover" className="w-full" style={{ aspectRatio: "9/16", objectFit: "cover" }} />
            <div className="p-2 text-[11px] text-teal">Grid cover</div>
          </div>
        )}
        {scenes.map((s: any) => {
          const img = `scene_${s.scene}.jpg`;
          const has = arts.includes(img);
          return (
            <div key={s.scene} className="glass overflow-hidden">
              <div className="relative bg-black/30 grid place-items-center" style={{ aspectRatio: "9/16" }}>
                {has ? (
                  /* eslint-disable-next-line @next/next/no-img-element */
                  <img src={api.artifactUrl(jobId, img)} alt={img} className="w-full h-full object-cover" />
                ) : (
                  <div className="p-3 text-center">
                    <div className="text-[11px] text-ink-faint mb-1">Scene {s.scene} · {s.seconds}s</div>
                    <div className="text-xs text-ink-muted">{s.on_screen}</div>
                  </div>
                )}
              </div>
              <div className="p-2">
                <div className="text-[11px] font-medium truncate">{s.on_screen || `Scene ${s.scene}`}</div>
                <div className="text-[10px] text-ink-faint truncate">{s.visual_beat}</div>
              </div>
            </div>
          );
        })}
      </div>
      {!hasCover && !arts.some((a) => a.startsWith("scene_")) && (
        <p className="text-[11px] text-mcp">Scene stills + cover are generated by Scene Studio / Cover Frame Studio (Higgsfield) in the Claude Code conductor — shown as the plan until then.</p>
      )}
    </div>
  );
}
