"""0001_initial_schema

Revision ID: 7726337f67ac
Revises: 
Create Date: 2026-05-08 02:00:37.655468

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7726337f67ac'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Required Postgres extensions (autogenerate is blind to these).
    # pgcrypto: gen_random_uuid() default for data_ingestion_runs.run_id.
    # pg_trgm:  GIN trigram index on stocks.company_name (added below).
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_ingestion_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'running'"), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=64), nullable=True),
    sa.Column('downloaded_at_utc', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('file_sha256', sa.CHAR(length=64), nullable=True),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.Column('source_trade_date', sa.Date(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status IN ('running','success','failed','partial')", name=op.f('ck_data_ingestion_runs_status_allowed')),
    sa.CheckConstraint('file_sha256 IS NULL OR length(file_sha256) = 64', name=op.f('ck_data_ingestion_runs_sha256_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_ingestion_runs')),
    sa.UniqueConstraint('run_id', name=op.f('uq_data_ingestion_runs_run_id'))
    )
    op.create_index('idx_ingestion_agent_started', 'data_ingestion_runs', ['agent_name', sa.literal_column('started_at DESC')], unique=False)
    op.create_index('idx_ingestion_failed', 'data_ingestion_runs', ['status', sa.literal_column('started_at DESC')], unique=False, postgresql_where=sa.text("status <> 'success'"))
    op.create_table('indices',
    sa.Column('index_code', sa.String(length=32), nullable=False),
    sa.Column('index_name', sa.String(length=120), nullable=False),
    sa.Column('index_type', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("index_type IN ('broad','sector','thematic')", name=op.f('ck_indices_index_type_allowed')),
    sa.PrimaryKeyConstraint('index_code', name=op.f('pk_indices'))
    )
    op.create_table('schema_version',
    sa.Column('version_label', sa.String(length=32), nullable=False),
    sa.Column('applied_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chunk_reference', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('version_label', name=op.f('pk_schema_version'))
    )
    op.create_table('stocks',
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('nse_symbol', sa.String(length=20), nullable=True),
    sa.Column('bse_symbol', sa.String(length=20), nullable=True),
    sa.Column('yfinance_symbol', sa.String(length=24), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('mcap_category', sa.String(length=8), nullable=True),
    sa.Column('mcap_inr_cr', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('listed_on', sa.Date(), nullable=True),
    sa.Column('delisted_on', sa.Date(), nullable=True),
    sa.Column('is_fno', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('lot_size_fno', sa.Integer(), nullable=True),
    sa.Column('last_refreshed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mcap_category IS NULL OR mcap_category IN ('large','mid','small','micro')", name=op.f('ck_stocks_mcap_category_allowed')),
    sa.CheckConstraint('delisted_on IS NULL OR listed_on IS NULL OR delisted_on >= listed_on', name=op.f('ck_stocks_delisted_after_listed')),
    sa.CheckConstraint('length(isin) = 12', name=op.f('ck_stocks_isin_length')),
    sa.PrimaryKeyConstraint('isin', name=op.f('pk_stocks'))
    )
    op.create_index('idx_stocks_active', 'stocks', ['delisted_on'], unique=False, postgresql_where=sa.text('delisted_on IS NULL'))
    op.create_index('idx_stocks_bse_symbol_active', 'stocks', ['bse_symbol'], unique=True, postgresql_where=sa.text('delisted_on IS NULL'))
    op.create_index('idx_stocks_nse_symbol_active', 'stocks', ['nse_symbol'], unique=True, postgresql_where=sa.text('delisted_on IS NULL'))
    op.create_index('idx_stocks_sector', 'stocks', ['sector'], unique=False)
    op.create_table('trading_calendar',
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('exchange', sa.String(length=8), server_default=sa.text("'NSE'"), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('session_type', sa.String(length=16), server_default=sa.text("'regular'"), nullable=False),
    sa.Column('holiday_name', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("NOT is_open OR session_type <> 'closed'", name=op.f('ck_trading_calendar_open_session_consistent')),
    sa.CheckConstraint("exchange IN ('NSE','BSE')", name=op.f('ck_trading_calendar_exchange_allowed')),
    sa.CheckConstraint("session_type IN ('regular','muhurat','closed')", name=op.f('ck_trading_calendar_session_type_allowed')),
    sa.PrimaryKeyConstraint('trade_date', 'exchange', name=op.f('pk_trading_calendar'))
    )
    op.create_index('idx_calendar_open', 'trading_calendar', ['exchange', 'trade_date'], unique=False, postgresql_where=sa.text('is_open'))
    op.create_table('corporate_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('action_type', sa.String(length=16), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('announcement_date', sa.Date(), nullable=True),
    sa.Column('ratio_numerator', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ratio_denominator', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('amount_inr', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action_type IN ('split','bonus','dividend','rights','spinoff','merger')", name=op.f('ck_corporate_actions_action_type_allowed')),
    sa.ForeignKeyConstraint(['isin'], ['stocks.isin'], name=op.f('fk_corporate_actions_isin_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corporate_actions')),
    sa.UniqueConstraint('isin', 'action_type', 'ex_date', name='corporate_actions_isin_type_exdate')
    )
    op.create_index('idx_ca_exdate', 'corporate_actions', ['ex_date'], unique=False)
    op.create_index('idx_ca_isin_exdate', 'corporate_actions', ['isin', sa.literal_column('ex_date DESC')], unique=False)
    op.create_table('data_quality_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.CheckConstraint("severity IN ('info','warn','error')", name=op.f('ck_data_quality_log_severity_allowed')),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['data_ingestion_runs.id'], name=op.f('fk_data_quality_log_ingestion_run_id_data_ingestion_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['isin'], ['stocks.isin'], name=op.f('fk_data_quality_log_isin_stocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_quality_log'))
    )
    op.create_index('idx_dql_code', 'data_quality_log', ['code', sa.literal_column('detected_at DESC')], unique=False)
    op.create_index('idx_dql_isin', 'data_quality_log', ['isin', sa.literal_column('detected_at DESC')], unique=False)
    op.create_index('idx_dql_open', 'data_quality_log', ['severity', sa.literal_column('detected_at DESC')], unique=False, postgresql_where=sa.text('resolved_at IS NULL'))
    op.create_table('index_constituents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('index_code', sa.String(length=32), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('weight_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('recorded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name=op.f('ck_index_constituents_effective_range')),
    sa.ForeignKeyConstraint(['index_code'], ['indices.index_code'], name=op.f('fk_index_constituents_index_code_indices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['isin'], ['stocks.isin'], name=op.f('fk_index_constituents_isin_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_index_constituents')),
    sa.UniqueConstraint('index_code', 'isin', 'effective_from', name='constituents_index_isin_effective_from')
    )
    op.create_index('idx_constituents_active', 'index_constituents', ['index_code', 'effective_to'], unique=False, postgresql_where=sa.text('effective_to IS NULL'))
    op.create_index('idx_constituents_isin_history', 'index_constituents', ['isin', sa.literal_column('effective_from DESC')], unique=False)
    op.create_index('idx_constituents_lookup', 'index_constituents', ['index_code', 'isin', sa.literal_column('effective_from DESC')], unique=False)
    op.create_table('prices_eod',
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('prev_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('turnover_inr', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('delivery_qty', sa.BigInteger(), nullable=True),
    sa.Column('delivery_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('trade_count', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('nse_bhavcopy','openalgo','yfinance')", name=op.f('ck_prices_eod_source_allowed')),
    sa.CheckConstraint('delivery_pct IS NULL OR (delivery_pct >= 0 AND delivery_pct <= 100)', name=op.f('ck_prices_eod_delivery_pct_range')),
    sa.CheckConstraint('high IS NULL OR low IS NULL OR high >= low', name=op.f('ck_prices_eod_high_ge_low')),
    sa.CheckConstraint('open IS NULL OR open >= 0', name=op.f('ck_prices_eod_open_non_negative')),
    sa.CheckConstraint('volume IS NULL OR volume >= 0', name=op.f('ck_prices_eod_volume_non_negative')),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['data_ingestion_runs.id'], name=op.f('fk_prices_eod_ingestion_run_id_data_ingestion_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['isin'], ['stocks.isin'], name=op.f('fk_prices_eod_isin_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('trade_date', 'isin', name=op.f('pk_prices_eod'))
    )
    op.create_index('idx_prices_eod_isin_date', 'prices_eod', ['isin', sa.literal_column('trade_date DESC')], unique=False)
    op.create_index('idx_prices_eod_source_date', 'prices_eod', ['source', sa.literal_column('trade_date DESC')], unique=False)
    op.create_table('stock_identifiers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('identifier_type', sa.String(length=24), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('recorded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.CheckConstraint("identifier_type IN ('nse_symbol','bse_symbol','company_name','industry','sector','mcap_category','lot_size_fno','is_fno')", name=op.f('ck_stock_identifiers_identifier_type_allowed')),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name=op.f('ck_stock_identifiers_effective_range')),
    sa.ForeignKeyConstraint(['isin'], ['stocks.isin'], name=op.f('fk_stock_identifiers_isin_stocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_identifiers')),
    sa.UniqueConstraint('isin', 'identifier_type', 'effective_from', name='stock_identifiers_isin_type_effective_from')
    )
    op.create_index('idx_stock_identifiers_current', 'stock_identifiers', ['isin', 'identifier_type'], unique=False, postgresql_where=sa.text('effective_to IS NULL'))
    op.create_index('idx_stock_identifiers_lookup', 'stock_identifiers', ['isin', 'identifier_type', sa.literal_column('effective_from DESC')], unique=False)
    op.create_index('idx_stock_identifiers_reverse', 'stock_identifiers', ['identifier_type', 'value'], unique=False)
    # ### end Alembic commands ###

    # Trigram GIN index on stocks.company_name — autogenerate is blind to
    # gin_trgm_ops, so this index is added by hand. Used by Universe Agent
    # and search endpoints for fuzzy company-name lookup.
    op.execute(
        "CREATE INDEX idx_stocks_name_trgm "
        "ON stocks USING gin (company_name gin_trgm_ops)"
    )

    # Operational migration log — final op of every migration per spec §3.3.
    op.execute(
        "INSERT INTO schema_version (version_label, description, chunk_reference) "
        "VALUES ("
        "'0001_initial_schema', "
        "'Initial schema for Phase 1: 10 tables, pgcrypto + pg_trgm extensions, "
        "GIN trigram index on stocks.company_name', "
        "'phase-1-chunk-1.1'"
        ")"
    )


def downgrade() -> None:
    # Remove the schema_version row first so a partial-rollback retry is clean.
    op.execute(
        "DELETE FROM schema_version WHERE version_label = '0001_initial_schema'"
    )
    # Drop the hand-added trigram index before dropping its table.
    op.execute("DROP INDEX IF EXISTS idx_stocks_name_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stock_identifiers_reverse', table_name='stock_identifiers')
    op.drop_index('idx_stock_identifiers_lookup', table_name='stock_identifiers')
    op.drop_index('idx_stock_identifiers_current', table_name='stock_identifiers', postgresql_where=sa.text('effective_to IS NULL'))
    op.drop_table('stock_identifiers')
    op.drop_index('idx_prices_eod_source_date', table_name='prices_eod')
    op.drop_index('idx_prices_eod_isin_date', table_name='prices_eod')
    op.drop_table('prices_eod')
    op.drop_index('idx_constituents_lookup', table_name='index_constituents')
    op.drop_index('idx_constituents_isin_history', table_name='index_constituents')
    op.drop_index('idx_constituents_active', table_name='index_constituents', postgresql_where=sa.text('effective_to IS NULL'))
    op.drop_table('index_constituents')
    op.drop_index('idx_dql_open', table_name='data_quality_log', postgresql_where=sa.text('resolved_at IS NULL'))
    op.drop_index('idx_dql_isin', table_name='data_quality_log')
    op.drop_index('idx_dql_code', table_name='data_quality_log')
    op.drop_table('data_quality_log')
    op.drop_index('idx_ca_isin_exdate', table_name='corporate_actions')
    op.drop_index('idx_ca_exdate', table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index('idx_calendar_open', table_name='trading_calendar', postgresql_where=sa.text('is_open'))
    op.drop_table('trading_calendar')
    op.drop_index('idx_stocks_sector', table_name='stocks')
    op.drop_index('idx_stocks_nse_symbol_active', table_name='stocks', postgresql_where=sa.text('delisted_on IS NULL'))
    op.drop_index('idx_stocks_bse_symbol_active', table_name='stocks', postgresql_where=sa.text('delisted_on IS NULL'))
    op.drop_index('idx_stocks_active', table_name='stocks', postgresql_where=sa.text('delisted_on IS NULL'))
    op.drop_table('stocks')
    op.drop_table('schema_version')
    op.drop_table('indices')
    op.drop_index('idx_ingestion_failed', table_name='data_ingestion_runs', postgresql_where=sa.text("status <> 'success'"))
    op.drop_index('idx_ingestion_agent_started', table_name='data_ingestion_runs')
    op.drop_table('data_ingestion_runs')
    # ### end Alembic commands ###

    # Drop required Postgres extensions last (after all dependent objects are gone).
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
