// Active-equity universe for the stock-mover leaderboard (v2: Nifty 500).
//
// Primary universe: the real Nifty 500 constituents, served from a committed snapshot
// (lib/maven/data/nifty500.json, generated by scripts/gen-nifty500.mjs from NSE's published,
// DOWNLOADABLE index-constituents CSV on nsearchives - the same permitted-file pattern
// nseUniverse.ts uses, not website scraping). A best-effort in-memory refresh (daily TTL) keeps
// constituents current where the fetch is reachable; on Vercel (datacenter IPs often blocked by
// NSE) the snapshot serves. Nifty 500 is EQ-series equities by construction - no ETFs, REITs,
// InvITs, indices, warrants or debt. Fallback: the v1 curated liquid list. Never fabricated.

import nifty500 from "./data/nifty500.json";

export type UniverseCoverage = "curated_liquid" | "nifty500" | "broad_liquid_nse" | "full_nse_attempted";

export type ActiveEquityUniverse = {
  symbols: { symbol: string; name: string }[];
  universeLabel: string;
  universeSize: number;
  coverage: UniverseCoverage;
  limitation?: string;
};

const N500_URL = "https://nsearchives.nseindia.com/content/indices/ind_nifty500list.csv";
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36";
const REFRESH_TTL = 24 * 60 * 60 * 1000;

type RawConstituent = { s: string; n: string; industry?: string };
let N500: { symbol: string; name: string }[] =
  ((nifty500 as any).constituents as RawConstituent[]).map((c) => ({ symbol: c.s, name: c.n }));
let lastRefresh = 0;

// Best-effort constituents refresh from the permitted downloadable CSV; snapshot serves on failure.
async function refreshNifty500(): Promise<void> {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), 8000);
  try {
    const r = await fetch(N500_URL, { headers: { "User-Agent": UA, Accept: "text/csv,*/*" }, signal: ctrl.signal, cache: "no-store" });
    if (!r.ok) return;
    const lines = (await r.text()).trim().split(/\r?\n/);
    const next: { symbol: string; name: string }[] = [];
    for (const line of lines.slice(1)) {
      const c = line.split(",").map((x) => x.trim());
      if (c.length < 5 || !c[2]) continue;
      if ((c[3] || "EQ").toUpperCase() !== "EQ") continue; // normal equity series only
      next.push({ symbol: c[2], name: c[0] });
    }
    if (next.length >= 400) { N500 = next; lastRefresh = Date.now(); }
  } catch {
    /* unreachable (e.g. datacenter IP blocked) -> keep committed snapshot, no user-facing error */
  } finally {
    clearTimeout(timer);
  }
}

// v1 curated liquid list - retained as the fallback universe. Symbols are NSE tickers (yahoo
// suffix .NS is appended by the scanner). Stale/renamed symbols return no quote and drop out.
const CURATED: { symbol: string; name: string }[] = [
  { symbol: "RELIANCE", name: "Reliance Industries" }, { symbol: "TCS", name: "Tata Consultancy Services" },
  { symbol: "HDFCBANK", name: "HDFC Bank" }, { symbol: "ICICIBANK", name: "ICICI Bank" },
  { symbol: "INFY", name: "Infosys" }, { symbol: "HINDUNILVR", name: "Hindustan Unilever" },
  { symbol: "ITC", name: "ITC" }, { symbol: "SBIN", name: "State Bank of India" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel" }, { symbol: "BAJFINANCE", name: "Bajaj Finance" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank" }, { symbol: "LT", name: "Larsen & Toubro" },
  { symbol: "HCLTECH", name: "HCL Technologies" }, { symbol: "AXISBANK", name: "Axis Bank" },
  { symbol: "ASIANPAINT", name: "Asian Paints" }, { symbol: "MARUTI", name: "Maruti Suzuki" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical" }, { symbol: "TITAN", name: "Titan Company" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement" }, { symbol: "WIPRO", name: "Wipro" },
  { symbol: "NESTLEIND", name: "Nestle India" }, { symbol: "ONGC", name: "Oil & Natural Gas Corp" },
  { symbol: "NTPC", name: "NTPC" }, { symbol: "POWERGRID", name: "Power Grid Corp" },
  { symbol: "TATAMOTORS", name: "Tata Motors" }, { symbol: "TATASTEEL", name: "Tata Steel" },
  { symbol: "JSWSTEEL", name: "JSW Steel" }, { symbol: "ADANIENT", name: "Adani Enterprises" },
  { symbol: "ADANIPORTS", name: "Adani Ports & SEZ" }, { symbol: "COALINDIA", name: "Coal India" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv" }, { symbol: "HDFCLIFE", name: "HDFC Life Insurance" },
  { symbol: "SBILIFE", name: "SBI Life Insurance" }, { symbol: "GRASIM", name: "Grasim Industries" },
  { symbol: "HINDALCO", name: "Hindalco Industries" }, { symbol: "DRREDDY", name: "Dr. Reddy's Labs" },
  { symbol: "CIPLA", name: "Cipla" }, { symbol: "BRITANNIA", name: "Britannia Industries" },
  { symbol: "EICHERMOT", name: "Eicher Motors" }, { symbol: "HEROMOTOCO", name: "Hero MotoCorp" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto" }, { symbol: "TECHM", name: "Tech Mahindra" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank" }, { symbol: "APOLLOHOSP", name: "Apollo Hospitals" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products" }, { symbol: "BPCL", name: "Bharat Petroleum" },
  { symbol: "LTIM", name: "LTIMindtree" }, { symbol: "SHRIRAMFIN", name: "Shriram Finance" },
  { symbol: "TRENT", name: "Trent" }, { symbol: "DMART", name: "Avenue Supermarts" },
  { symbol: "PIDILITIND", name: "Pidilite Industries" }, { symbol: "DABUR", name: "Dabur India" },
  { symbol: "GAIL", name: "GAIL India" }, { symbol: "IOC", name: "Indian Oil Corp" },
  { symbol: "VEDL", name: "Vedanta" }, { symbol: "HAL", name: "Hindustan Aeronautics" },
  { symbol: "BEL", name: "Bharat Electronics" }, { symbol: "SIEMENS", name: "Siemens" },
  { symbol: "VBL", name: "Varun Beverages" }, { symbol: "PFC", name: "Power Finance Corp" },
  { symbol: "IRCTC", name: "IRCTC" }, { symbol: "ZOMATO", name: "Eternal (Zomato)" },
];

/**
 * The active-equity universe the mover scanner ranks within.
 * v2 primary: real Nifty 500 constituents (committed snapshot + best-effort daily refresh).
 * Fallback: the v1 curated liquid list (only if the snapshot is somehow unusable).
 */
export async function getActiveEquityUniverse(): Promise<ActiveEquityUniverse> {
  if (Date.now() - lastRefresh > REFRESH_TTL) void refreshNifty500(); // fire-and-forget; snapshot serves immediately
  if (N500.length >= 400) {
    return {
      symbols: N500,
      universeLabel: "Nifty 500",
      universeSize: N500.length,
      coverage: "nifty500",
      limitation: undefined, // coverage wording is added by the scanner with real scan counts
    };
  }
  return {
    symbols: CURATED,
    universeLabel: "curated liquid NSE equities",
    universeSize: CURATED.length,
    coverage: "curated_liquid",
    limitation: "Ranked within a curated liquid NSE-equity universe, not the full NSE list.",
  };
}
