"""Step — Higgsfield Animated Scene Generator (PAID, gated).

The primary video source for the reel: 5-6 animated 9:16 clips, one per planned
shot (image-seed -> animate). This module NEVER calls Higgsfield itself — the
Python backend cannot reach paid MCP tools. It follows the same honesty pattern
as the retired Fresh Video Mode (which it replaces):

  1. plan() — deterministic + FREE. Cost preflight + gate decision. Called by
     the orchestrator. Never generates anything.
  2. approve_from_ui() — records the operator's explicit UI trigger (Run Reel /
     Regenerate buttons). Still generates nothing.
  3. record_results() — called by the Claude Code conductor AFTER it actually
     generates + downloads each clip via Higgsfield MCP; verifies files on disk
     and persists the auditable outcome (job ids, real cost, retries).

Gate: generation may only execute when approved_from_ui (or explicit operator
approval) AND projected cost <= HIGGSFIELD_MAX_CREDITS_PER_REEL. Claude Code
must never auto-execute during implementation (ALLOW_PAID_HIGGSFIELD_FROM_CLAUDE_CODE=false).
"""
from __future__ import annotations

from pathlib import Path

from . import config, state

CLIPS_DIR = "higgsfield_clips"


def _scene_cost(p: dict) -> float:
    """Per-scene cost from the model router; seed still added only when the
    image_seed method is configured."""
    clip = float(p.get("estimated_cost") or config.HIGGSFIELD_CLIP_COST_CREDITS)
    seed = (config.HIGGSFIELD_SEED_COST_CREDITS
            if config.HIGGSFIELD_GENERATION_METHOD == "image_seed" else 0.0)
    return clip + seed


def plan(date: str, *, shot_prompts: dict, renderer: dict) -> dict:
    """Deterministic + free: the generation plan + gate decision."""
    prompts = shot_prompts.get("shot_prompts", [])[: config.MAX_HIGGSFIELD_SCENES_PER_REEL]
    est = round(sum(_scene_cost(p) for p in prompts), 1)
    over_budget = est > config.MAX_REEL_GENERATION_COST
    is_primary = renderer.get("renderer") == "higgsfield_primary"

    status = ("not_selected" if not is_primary else
              "over_budget" if over_budget else
              "requires_user_action")
    payload = {
        "date": date,
        "clips_dir": CLIPS_DIR,
        "method": shot_prompts.get("method", config.HIGGSFIELD_GENERATION_METHOD),
        "planned": [{"shot_id": p["shot_id"],
                     "clip_path": f"{CLIPS_DIR}/{p['shot_id']}.mp4",
                     "duration": p["duration"],
                     "model": p["model_recommendation"],
                     "fallback_model": p.get("fallback_model"),
                     "scene_complexity": p.get("scene_complexity"),
                     "estimated_cost": round(_scene_cost(p), 1)} for p in prompts],
        "total_clips": len(prompts),
        "estimated_cost_credits": est,
        "max_credits_per_reel": config.HIGGSFIELD_MAX_CREDITS_PER_REEL,
        "generation_status": status,
        "approved_from_ui": False,
        "reason": ("Higgsfield primary renderer awaiting operator trigger — paid "
                   "generation only runs after an explicit UI action, executed by "
                   "the Claude Code conductor." if status == "requires_user_action"
                   else f"Projected {est}cr exceeds the {config.HIGGSFIELD_MAX_CREDITS_PER_REEL}cr "
                        "ceiling." if over_budget else
                   "Renderer is not higgsfield_primary."),
        "clips": [],
    }
    state.save_artifact(date, "scene_generation", payload)
    return payload


def approve_from_ui(date: str, *, shot_ids: list[str] | None = None,
                    source: str = "ui_run_reel") -> dict:
    """Record the operator's explicit paid-generation trigger (UI button).
    Generates nothing — flips the gate so the conductor may execute."""
    gen = state.load_artifact(date, "scene_generation")
    if gen["generation_status"] == "over_budget":
        return gen  # ceiling wins even over an approval click
    gen["approved_from_ui"] = True
    gen["approval_source"] = source
    gen["approved_shot_ids"] = shot_ids or [p["shot_id"] for p in gen["planned"]]
    gen["generation_status"] = "approved_awaiting_conductor"
    gen["reason"] = ("Operator approved paid generation from the UI. The Claude "
                     "Code conductor executes the Higgsfield MCP calls next — "
                     "nothing is generated by the backend itself.")
    state.save_artifact(date, "scene_generation", gen)
    return gen


def record_results(date: str, results: list[dict]) -> dict:
    """Conductor calls this after REAL generation. Each result:
    {shot_id, clip_path, duration, status, higgsfield_job_id, seed_job_id,
     prompt_used, model_used, cost_credits, retries, failure_reason?}.
    Verifies files exist on disk before accepting 'completed'."""
    gen = state.load_artifact(date, "scene_generation")
    run_dir = config.run_dir(date)
    verified = []
    for r in results:
        r = dict(r)
        p = run_dir / r.get("clip_path", "")
        r["file_exists"] = p.exists()
        if r.get("status") == "completed" and not r["file_exists"]:
            r["status"] = "failed"
            r["failure_reason"] = "clip missing on disk after generation"
        verified.append(r)

    done = [r for r in verified if r.get("status") == "completed"]
    gen["clips"] = verified
    gen["completed_clips"] = len(done)
    gen["failed_clips"] = len(verified) - len(done)
    gen["actual_cost_credits"] = round(sum(r.get("cost_credits", 0) for r in verified), 1)
    gen["generation_status"] = ("completed" if done and not gen["failed_clips"]
                                else "partial" if done else "failed")
    state.save_artifact(date, "scene_generation", gen)
    return gen


def clips_on_disk(date: str) -> list[Path]:
    d = config.run_dir(date) / CLIPS_DIR
    return sorted(d.glob("shot_*.mp4")) if d.exists() else []
