"""The 22-node Reels registry — premium UI names mapped to real components.

Same honesty contract as the carousel registry (classes A-G + intelligent flag),
tuned for the retention-first Reels pipeline. `pipeline = "reel"`.
"""
from __future__ import annotations

from .registry import CLASS_LABELS  # reuse the shared A-G labels

REEL_NODES: list[dict] = [
    {"node_id": "closing_bell", "name": "Closing Bell", "order": 0,
     "component_class": "G", "component_type": "Scheduler", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "5 PM cron / trigger",
     "role": "Starts the post-market reel workflow."},
    {"node_id": "claude_conductor", "name": "Claude Conductor", "order": 1,
     "component_class": "F", "component_type": "LLM Runtime", "intelligent": True,
     "external": False, "in_graph": True, "actual_component": "Claude Code runtime",
     "role": "Bridges Python, Higgsfield (stills+TTS), ffmpeg and Composio Reels."},
    {"node_id": "market_sentinel", "name": "Market Sentinel", "order": 2,
     "component_class": "A", "component_type": "LLM Agent", "intelligent": True,
     "external": False, "in_graph": True,
     "actual_component": "ReelResearch LLM (web)",
     "role": "Finds stories that are important AND emotional/simple/visual."},
    {"node_id": "viral_fit", "name": "Viral Fit Gate", "order": 3,
     "component_class": "B", "component_type": "Guardrail", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "step02_viral_fit.py",
     "role": "Scores 7 dims, picks the best REEL story (not just the important one)."},
    {"node_id": "angle_studio", "name": "Angle Studio", "order": 4,
     "component_class": "A", "component_type": "LLM Agent", "intelligent": True,
     "external": False, "in_graph": True, "actual_component": "step03_angle.py",
     "role": "Turns the story into a scroll-stopping idea."},
    {"node_id": "hook_lab", "name": "Hook Lab", "order": 5,
     "component_class": "A", "component_type": "LLM Agent", "intelligent": True,
     "external": False, "in_graph": True, "actual_component": "step04_hooks.py",
     "role": "7 hook buckets, scored; picks the strongest 2-second hook."},
    {"node_id": "script_room", "name": "Script Room", "order": 6,
     "component_class": "A", "component_type": "LLM Agent", "intelligent": True,
     "external": False, "in_graph": True, "actual_component": "step05_script.py",
     "role": "Timed 20-35s script (hook/what/why/understand/CTA)."},
    {"node_id": "retention_editor", "name": "Retention Editor", "order": 7,
     "component_class": "A", "component_type": "LLM Agent", "intelligent": True,
     "external": False, "in_graph": True, "actual_component": "step06_retention.py",
     "role": "Cuts filler, adds pattern interrupts, keeps it under 35s and fast."},
    {"node_id": "storyboard", "name": "Storyboard", "order": 8,
     "component_class": "B", "component_type": "Python Module", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "step07_storyboard.py",
     "role": "5-7 scenes: on-screen text + duration + visual beat."},
    {"node_id": "visual_director", "name": "Visual Director", "order": 9,
     "component_class": "B", "component_type": "Python Module", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "step08_visual_direction.py",
     "role": "Picks the dark-finance scene design system."},
    {"node_id": "scene_studio", "name": "Scene Studio", "order": 10,
     "component_class": "C", "component_type": "MCP Service", "intelligent": False,
     "external": True, "in_graph": True,
     "actual_component": "Higgsfield nano_banana_pro (9:16 stills)",
     "role": "Generates premium 9:16 background frames."},
    {"node_id": "voice_studio", "name": "Voice Studio", "order": 11,
     "component_class": "C", "component_type": "MCP Service", "intelligent": False,
     "external": True, "in_graph": True,
     "actual_component": "Higgsfield TTS (text2speech_v2_*)",
     "role": "Calm, confident AI voiceover from the script."},
    {"node_id": "subtitle_engine", "name": "Subtitle Engine", "order": 12,
     "component_class": "B", "component_type": "Python Module", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "step11_subtitles.py",
     "role": "Builds burned-in captions.srt timing."},
    {"node_id": "cut_room", "name": "Cut Room", "order": 13,
     "component_class": "Cprime", "component_type": "Local DSP / Video", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "step12_cut.py (ffmpeg)",
     "role": "Ken-Burns scenes + subs + voiceover + music -> reel.mp4."},
    {"node_id": "cover_studio", "name": "Cover Frame Studio", "order": 14,
     "component_class": "C", "component_type": "MCP Service", "intelligent": False,
     "external": True, "in_graph": True,
     "actual_component": "Higgsfield still -> cover.jpg",
     "role": "Premium grid cover / first frame."},
    {"node_id": "caption_desk", "name": "Caption Desk", "order": 15,
     "component_class": "B", "component_type": "Python Module", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "step14_caption.py",
     "role": "Reel caption + hashtags + disclaimer."},
    {"node_id": "compliance_shield", "name": "Compliance Shield", "order": 16,
     "component_class": "B", "component_type": "Guardrail", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "compliance.py (reused)",
     "role": "Blocks advice, hype, fake claims across all reel text."},
    {"node_id": "reel_auditor", "name": "Reel Auditor", "order": 17,
     "component_class": "B", "component_type": "Quality Gate", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "step16_quality.py",
     "role": "Hook / Retention / Visual / Compliance / Publish scores + gate."},
    {"node_id": "publish_gate", "name": "Publish Gate", "order": 18,
     "component_class": "B", "component_type": "Python Module", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "step17_publish.preflight",
     "role": "Final preflight before publishing."},
    {"node_id": "reels_courier", "name": "Reels Courier", "order": 19,
     "component_class": "D", "component_type": "Publisher", "intelligent": False,
     "external": True, "in_graph": True,
     "actual_component": "Composio -> Instagram Reels (media_type=REELS)",
     "role": "Uploads and publishes the Reel; returns the permalink."},
    {"node_id": "signal_tracker", "name": "Signal Tracker", "order": 20,
     "component_class": "C", "component_type": "External MCP Service", "intelligent": False,
     "external": True, "in_graph": True,
     "actual_component": "Composio IG insights / analytics.py",
     "role": "Tracks 3s retention, watch time, replays, saves, shares; learns."},
    {"node_id": "run_vault", "name": "Run Vault", "order": 21,
     "component_class": "E", "component_type": "State System", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "state.py / artifacts",
     "role": "Stores every reel artifact, score, log and state update."},
]

REEL_NODES_BY_ID = {n["node_id"]: n for n in REEL_NODES}
REEL_GRAPH_ORDER = [n["node_id"] for n in sorted(REEL_NODES, key=lambda n: n["order"])
                    if n["in_graph"]]


def reel_node(node_id: str) -> dict:
    return REEL_NODES_BY_ID.get(node_id, {
        "node_id": node_id, "name": node_id, "component_class": "B",
        "component_type": "Python Module", "intelligent": False,
        "external": False, "in_graph": False, "actual_component": "", "role": "",
    })
