"""The 21-node Reels registry (upgraded motion pipeline) — premium UI names
mapped to real components. Same honesty contract as the carousel (classes A-G +
intelligent flag). Remotion/ffmpeg are marked as a Video Rendering Engine.
"""
from __future__ import annotations

from .registry import CLASS_LABELS  # reuse shared A-G labels

REEL_NODES: list[dict] = [
    {"node_id": "closing_bell", "name": "Closing Bell", "order": 0,
     "component_class": "G", "component_type": "Scheduler", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "5 PM cron / trigger",
     "role": "Starts the post-market reel workflow."},
    {"node_id": "market_sentinel", "name": "Market Sentinel", "order": 1,
     "component_class": "A", "component_type": "LLM Agent", "intelligent": True,
     "external": False, "in_graph": True, "actual_component": "ReelResearch LLM (web)",
     "role": "Finds stories that are important AND emotional/simple/visual."},
    {"node_id": "viral_fit", "name": "Viral Fit Gate", "order": 2,
     "component_class": "B", "component_type": "Guardrail", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "step02_viral_fit.py",
     "role": "Scores 9 traits, picks the best REEL story (not just the important one)."},
    {"node_id": "angle_studio", "name": "Angle Studio", "order": 3,
     "component_class": "A", "component_type": "LLM Agent", "intelligent": True,
     "external": False, "in_graph": True, "actual_component": "step03_angle.py",
     "role": "Generates 8-12 angles, scores scroll-stop, picks the best."},
    {"node_id": "hook_lab", "name": "Hook Lab", "order": 4,
     "component_class": "A", "component_type": "LLM Agent", "intelligent": True,
     "external": False, "in_graph": True, "actual_component": "step04_hooks.py",
     "role": "15 hooks across categories; strongest 0.3s hook chosen."},
    {"node_id": "script_room", "name": "Script Room", "order": 5,
     "component_class": "A", "component_type": "LLM Agent", "intelligent": True,
     "external": False, "in_graph": True, "actual_component": "step05_script.py",
     "role": "Tight 15-20s script (45-65 words), beat-timed."},
    {"node_id": "retention_editor", "name": "Retention Editor", "order": 6,
     "component_class": "A", "component_type": "LLM Agent", "intelligent": True,
     "external": False, "in_graph": True, "actual_component": "step06_retention.py",
     "role": "Cuts filler, pattern interrupts every 2-3s, keeps it fast."},
    {"node_id": "template_selector", "name": "Template Selector", "order": 7,
     "component_class": "B", "component_type": "Deterministic Module", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "step_template_selector.py",
     "role": "Picks 1 of 5 reel templates + scene structure for the story."},
    {"node_id": "motion_variation", "name": "Motion Variation", "order": 8,
     "component_class": "B", "component_type": "Deterministic Module", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "step_motion_variation.py",
     "role": "Varies accent/motion for a unique look — zero new generation."},
    {"node_id": "motion_storyboard", "name": "Motion Storyboard", "order": 9,
     "component_class": "B", "component_type": "Deterministic Module", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "step6_motion_storyboard.py",
     "role": "8-12 fast micro-scenes mapped to animated scene kinds."},
    {"node_id": "asset_director", "name": "Asset Director", "order": 10,
     "component_class": "B", "component_type": "Deterministic Module", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "step7_asset_director.py",
     "role": "Decides the reusable visual assets the motion edit needs."},
    {"node_id": "asset_picker", "name": "Asset Picker", "order": 11,
     "component_class": "B", "component_type": "Deterministic Module", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "step_asset_picker.py",
     "role": "Reuses library plates (0 paid generation); flags gaps for approval."},
    {"node_id": "cost_guard", "name": "Cost Guard", "order": 12,
     "component_class": "B", "component_type": "Guardrail", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "step_cost_guard.py",
     "role": "Blocks paid Higgsfield generation unless explicitly approved."},
    {"node_id": "scene_studio", "name": "Scene Studio", "order": 13,
     "component_class": "C", "component_type": "External MCP Service", "intelligent": False,
     "external": True, "in_graph": True,
     "actual_component": "Higgsfield nano_banana_pro (9:16 clean assets)",
     "role": "Generates 3-6 premium background assets (no baked text)."},
    {"node_id": "motion_graphics", "name": "Motion Graphics Engine", "order": 10,
     "component_class": "Cprime", "component_type": "Video Rendering Engine", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "Remotion + ffmpeg",
     "role": "Renders the animated 1080x1920 motion edit (typography, counters, charts)."},
    {"node_id": "voice_studio", "name": "Voice Studio", "order": 11,
     "component_class": "C", "component_type": "External MCP Service", "intelligent": False,
     "external": True, "in_graph": True, "actual_component": "Higgsfield TTS (seed_audio)",
     "role": "Clear, energetic-but-premium AI voiceover fit to the edit."},
    {"node_id": "subtitle_engine", "name": "Subtitle Engine", "order": 12,
     "component_class": "B", "component_type": "Deterministic Module", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "step11_subtitles.py",
     "role": "Kinetic burned subtitles, key-word emphasis, synced timing."},
    {"node_id": "sound_design", "name": "Sound Design Desk", "order": 13,
     "component_class": "Cprime", "component_type": "Video Rendering Engine", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "step_sound_design.py (ffmpeg)",
     "role": "Original music bed + SFX + ducking under the voiceover."},
    {"node_id": "cover_studio", "name": "Cover Frame Studio", "order": 14,
     "component_class": "Cprime", "component_type": "Video Rendering Engine", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "Remotion hook frame -> cover.jpg",
     "role": "Strong 3-6 word grid cover from the animated hook."},
    {"node_id": "reel_auditor", "name": "Reel Auditor", "order": 15,
     "component_class": "B", "component_type": "Quality Gate", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "step16_quality.py",
     "role": "9 strict scores; blocks low-quality output and reroutes."},
    {"node_id": "approval", "name": "Telegram / UI Approval", "order": 16,
     "component_class": "B", "component_type": "Human Approval", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "Newsroom UI / Telegram",
     "role": "Human approves the reel before anything is published."},
    {"node_id": "publish_gate", "name": "Publish Gate", "order": 17,
     "component_class": "B", "component_type": "Deterministic Module", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "step17_publish.preflight",
     "role": "Final preflight: gate passed + approved + assets exist."},
    {"node_id": "reels_courier", "name": "Reels Courier", "order": 18,
     "component_class": "D", "component_type": "Publisher", "intelligent": False,
     "external": True, "in_graph": True,
     "actual_component": "Composio -> Instagram Reels (media_type=REELS)",
     "role": "Uploads and publishes the Reel; returns the permalink."},
    {"node_id": "signal_tracker", "name": "Signal Tracker", "order": 19,
     "component_class": "C", "component_type": "External MCP Service", "intelligent": False,
     "external": True, "in_graph": True,
     "actual_component": "Composio IG insights / analytics.py",
     "role": "Tracks 3s retention, watch time, saves, shares; recommends."},
    {"node_id": "run_vault", "name": "Run Vault", "order": 20,
     "component_class": "E", "component_type": "State System", "intelligent": False,
     "external": False, "in_graph": True, "actual_component": "state.py / artifacts",
     "role": "Stores every reel artifact, score, log and state update."},
]

# Normalize order to list position so inserting nodes never requires renumbering.
for _i, _n in enumerate(REEL_NODES):
    _n["order"] = _i

REEL_NODES_BY_ID = {n["node_id"]: n for n in REEL_NODES}
REEL_GRAPH_ORDER = [n["node_id"] for n in sorted(REEL_NODES, key=lambda n: n["order"])
                    if n["in_graph"]]


def reel_node(node_id: str) -> dict:
    return REEL_NODES_BY_ID.get(node_id, {
        "node_id": node_id, "name": node_id, "component_class": "B",
        "component_type": "Deterministic Module", "intelligent": False,
        "external": False, "in_graph": False, "actual_component": "", "role": "",
    })
